// Writes the catalogue in src/lib/catalog.js (items, areas, auto landmarks) as a
// Supabase migration, so report ids in the database always match the app.
// Run it after changing catalog.js:  npm run db:catalog  then  npx supabase db push
import { writeFileSync } from 'node:fs';
import { AREAS, ITEMS, PLACES } from '../src/lib/catalog.js';

const q = v => (v == null ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replaceAll("'", "''")}'`);
const rows = list => list.map(r => `  (${r.map(q).join(', ')})`).join(',\n');

const sql = `-- Generated by scripts/catalog-sql.mjs from src/lib/catalog.js. Don't edit by hand.
insert into public.items (id, name, name_ml, name_hi, category, unit) values
${rows(ITEMS.map(i => [i.id, i.name, i.ml, i.hi, i.cat, i.unit]))}
on conflict (id) do update set name = excluded.name, name_ml = excluded.name_ml, name_hi = excluded.name_hi,
  category = excluded.category, unit = excluded.unit;

insert into public.areas (id, name) values
${rows(AREAS.map(a => [a.id, a.name]))}
on conflict (id) do update set name = excluded.name;

-- Areas no longer in the app. Fails (on purpose) if any report still uses one.
delete from public.areas where id not in (${AREAS.map(a => q(a.id)).join(', ')});

insert into public.places (id, name, name_ml, lat, lng) values
${rows(PLACES.map(p => [p.id, p.name, p.ml, p.lat, p.lng]))}
on conflict (id) do update set name = excluded.name, name_ml = excluded.name_ml, lat = excluded.lat, lng = excluded.lng;
`;

const stamp = process.argv[2] ?? new Date().toISOString().replace(/\D/g, '').slice(0, 14);
const file = new URL(`../supabase/migrations/${stamp}_catalog_rows.sql`, import.meta.url);
writeFileSync(file, sql);
console.log(`Wrote supabase/migrations/${stamp}_catalog_rows.sql (${ITEMS.length} items, ${AREAS.length} areas, ${PLACES.length} places)`);
